### ISSUE TITLE
The connection is not persistent

### ISSUE THREAD

**Issue by rakeshR7** [joewalnes/websocketd#307] opened 2018-05-25 15:55 UTC
I followed the tutorial and noticed that as soon as the server finishes execution, it disconnects. Is there a way to keep the socket open forever? ReconnectingWebSocket doesn't seem to be working for me. can you help as soon as possible? please?

**Comment by asergeyev** [comment] 2018-05-25 16:51
If your script ends connection will close.  If user moves on to other page connection will close.

**Comment by rakeshR7** [comment] 2018-05-25 17:47
How do i make the connection not close when the user is on the same page?

**Comment by asergeyev** [comment] 2018-07-02 13:13
I'm not sure I can answer without knowing what you're trying to do and how HTML/JS code looks like.

**Comment by ldxsdyx** [comment] 2018-07-27 08:57
yes, I get the same problem. It's like close the connection after 3 second received some message from client.

**Comment by ldxsdyx** [comment] 2018-07-27 08:59
Yes, I get the same problem. It's like websocketd will actively close the connection witch have not receive any  message in 3 seconds, Can I close this feature?

**Comment by ldxsdyx** [comment] 2018-07-27 09:02
Yes, I get the same problem. It's like websocketd will actively close the connection witch have not receive any message in 3 seconds, Can I close this feature? @asergeyev @joewalnes

**Comment by sectokia** [comment] 2018-07-30 11:21
If the command the server is running finishes, the server will disconnect.
If the client closes, obviously it disconnects as well.

It makes no sense to "keep persistent", as there is no longer anything to run so nothing can possibly happen apart from the client sending data to the server. If you want the server command to wait until it gets another message, just have it read stdin instead of exiting.

**Comment by asergeyev** [comment] 2018-08-12 13:30
@sectokia describes intended behavior so if you see that things work differently, please re-open with more context (OS, version, code you not shy to share, etc)

**Closed by asergeyev** 2018-08-12 13:30 UTC
